### ISSUE TITLE
get-azurehdinsightclsuter location wrong

### ISSUE THREAD

**Issue by mumian** [PKRoma/hadoopsdk#2]
The location information is wrong.  It lists the username:

PS C:> get-azurehdinsightcluster HDI0819 -Subscriptionid $subid -certificate $cert

Name               : HDI0819
ConnectionUrl      : https://HDI0819.azurehdinsight.net
State              : Running
CreateDate         : 8/19/2013 5:33:10 PM
UserName           : admin
Location           : admin
ClusterSizeInNodes : 1

**Comment by PKRoma** [comment]
This is a mirror of the Microsoft .NET SDK For Hadoop repository on CodePlex and issues entered in this mirror repository will not be seen by the original developers. Please re-enter your issue in the original repository at http://hadoopsdk.codeplex.com/.
